/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.AbogadoAdminDAO;
import Controlador.AbogadoDefensorDAO;
import Controlador.AbogadoEstudiosCausasDAO;
import Modelo.Abogado_administrador;
import Modelo.Abogado_defensor_tribunales;
import Modelo.Abogado_estudio_causas;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author XPS 9560
 */
public class Inicio_programa extends javax.swing.JFrame {

    /**
     * Creates new form Inicio_sescion
     */
    public Inicio_programa() {
        initComponents();
        ROL.addItem("Abogado administrador");
        ROL.addItem("Abogado estudio de causas");
        ROL.addItem("Abogado defensor en tribunales");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        contrasena = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        usuario = new javax.swing.JTextPane();
        salir = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ingresar = new javax.swing.JButton();
        registrarse = new javax.swing.JButton();
        ROL = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 204));
        jLabel1.setText("Bienvenido al programa de abogados empresa LEX");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ingrese sus credenciales acceso al sistema", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 36), new java.awt.Color(0, 153, 153))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/logo_1.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel3.setText("Contraseña:");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel4.setText("Rol:");

        jScrollPane1.setViewportView(contrasena);

        jScrollPane2.setViewportView(usuario);

        salir.setBackground(new java.awt.Color(153, 0, 0));
        salir.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        salir.setForeground(new java.awt.Color(255, 102, 51));
        salir.setText("Salir del programa");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel5.setText("ingrese aqui");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel6.setText("Si no se ha registrado en el sistema");

        ingresar.setBackground(new java.awt.Color(51, 204, 0));
        ingresar.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        ingresar.setForeground(new java.awt.Color(0, 0, 0));
        ingresar.setText("Ingresar");
        ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresarActionPerformed(evt);
            }
        });

        registrarse.setBackground(new java.awt.Color(153, 153, 0));
        registrarse.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        registrarse.setForeground(new java.awt.Color(0, 0, 0));
        registrarse.setText("Registrarse");
        registrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarseActionPerformed(evt);
            }
        });

        ROL.setBackground(new java.awt.Color(51, 102, 0));
        ROL.setEditable(true);
        ROL.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        ROL.setForeground(new java.awt.Color(0, 204, 0));
        ROL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ROLActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel7.setText("Usuario:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 779, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(109, 109, 109)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(218, 218, 218)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 634, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(70, 70, 70)
                                    .addComponent(ingresar, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(61, 61, 61)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addGap(46, 46, 46)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ROL, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(90, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(1094, Short.MAX_VALUE)
                    .addComponent(registrarse, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(280, 280, 280)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(871, Short.MAX_VALUE)
                    .addComponent(jLabel7)
                    .addGap(651, 651, 651)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 779, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ROL, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(66, 66, 66)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(60, 60, 60)
                        .addComponent(ingresar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(758, Short.MAX_VALUE)
                    .addComponent(registrarse, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(111, 111, 111)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(187, 187, 187)
                    .addComponent(jLabel7)
                    .addContainerGap(730, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(143, 143, 143))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        int ret;
        Object[] opciones={"Sí","No"};
        String men="Desea salir del programa LEX? ";
        String tit="SALIR";
        ret=JOptionPane.showOptionDialog(null,men,tit,JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,null,opciones, opciones[0]);
            if(ret==JOptionPane.YES_OPTION)
                System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void ingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresarActionPerformed
        String us;
        String pass;
        String rol;
        us=usuario.getText();
        pass=contrasena.getText();
        rol=(String) ROL.getSelectedItem();
        AbogadoAdminDAO ad=new AbogadoAdminDAO();
        AbogadoDefensorDAO adef=new AbogadoDefensorDAO();
        AbogadoEstudiosCausasDAO est=new AbogadoEstudiosCausasDAO();
        Abogado_administrador a=new Abogado_administrador(pass, us, pass);
        Abogado_defensor_tribunales d=new Abogado_defensor_tribunales(pass, us, pass);
        Abogado_estudio_causas e=new Abogado_estudio_causas(pass, us, pass);
        if(rol=="Abogado administrador")
        {
            if(ad.Validar_conexion_abogado_admin(us, pass)!=null)
            {
                JOptionPane.showMessageDialog(this, a.iniciar_sesion(us, pass), "Inicio de secion", JOptionPane.INFORMATION_MESSAGE);
                Menu_abogado_admin ma=new Menu_abogado_admin();
                ma.setLocationRelativeTo(null);
                ma.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
                ma.setTitle("Menu abogado administrador");
                ma.setVisible(true);
                
            }
            else
            {
                JOptionPane.showMessageDialog(this, a.iniciar_sesion(us, pass), "Inicio de secion", JOptionPane.INFORMATION_MESSAGE);
            }
        }
        if(rol=="Abogado estudio de causas")
        {
            if(est.Validar_conexion_abogado_estudio_causas(us, pass)!=null)
            {
                JOptionPane.showMessageDialog(this, e.iniciar_sesion(us, pass), "Inicio de secion", JOptionPane.INFORMATION_MESSAGE);
                Menu_abogado_estudio_causas mc=new Menu_abogado_estudio_causas();
                mc.setLocationRelativeTo(null);
                mc.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
                mc.setTitle("Menu abogado estudio de causas");
                mc.setVisible(true);
            }
            else
            {
                JOptionPane.showMessageDialog(this, e.iniciar_sesion(us, pass), "Inicio de secion", JOptionPane.INFORMATION_MESSAGE);
            }
        }
        if(rol=="Abogado defensor en tribunales")
        {
            if(adef.Validar_conexion_abogado_defensor(us, pass)!=null)
            {
                JOptionPane.showMessageDialog(this, d.iniciar_sesion(us, pass), "Inicio de secion", JOptionPane.INFORMATION_MESSAGE);
                Mneu_defensor md=new Mneu_defensor();
                md.setLocationRelativeTo(null);
                md.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
                md.setTitle("Menu abaogado defensor en tribunales");
                
            }
            else
            {
                JOptionPane.showMessageDialog(this, d.iniciar_sesion(us, pass), "Inicio de secion", JOptionPane.INFORMATION_MESSAGE);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Error!! debe seleccionar su rol para para poder ingresar al sistema", "Inicio de secion", JOptionPane.INFORMATION_MESSAGE);
        }
        
      
    }//GEN-LAST:event_ingresarActionPerformed

    private void registrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarseActionPerformed
        Registro reg=new Registro();
        reg.setLocationRelativeTo(null);
        reg.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        reg.setTitle("Registro de abogados");
        reg.setVisible(true);
        
    }//GEN-LAST:event_registrarseActionPerformed

    private void ROLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ROLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ROLActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ROL;
    private javax.swing.JTextPane contrasena;
    private javax.swing.JButton ingresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton registrarse;
    private javax.swing.JButton salir;
    private javax.swing.JTextPane usuario;
    // End of variables declaration//GEN-END:variables
}
