/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author XPS 9560
 */
public class Menu_abogado_estudio_causas extends javax.swing.JFrame {

    /**
     * Creates new form Menu_abogado_estudio_causas
     */
    public Menu_abogado_estudio_causas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        agregar_info = new javax.swing.JButton();
        consultar_info = new javax.swing.JButton();
        crear_instructivo = new javax.swing.JButton();
        buscar_atecedentes = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 102));
        jLabel1.setText("Menu abogado estudio de causas");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Opciones a elegir", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 36), new java.awt.Color(51, 153, 0))); // NOI18N

        agregar_info.setBackground(new java.awt.Color(0, 102, 0));
        agregar_info.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        agregar_info.setText("Agregar informacion");
        agregar_info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregar_infoActionPerformed(evt);
            }
        });

        consultar_info.setBackground(new java.awt.Color(0, 102, 0));
        consultar_info.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        consultar_info.setText("Conultar informacion");
        consultar_info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultar_infoActionPerformed(evt);
            }
        });

        crear_instructivo.setBackground(new java.awt.Color(0, 102, 0));
        crear_instructivo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        crear_instructivo.setText("Crear instructivo de causas");
        crear_instructivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crear_instructivoActionPerformed(evt);
            }
        });

        buscar_atecedentes.setBackground(new java.awt.Color(0, 102, 0));
        buscar_atecedentes.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        buscar_atecedentes.setText("Buscar antecedentes de causa");
        buscar_atecedentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscar_atecedentesActionPerformed(evt);
            }
        });

        salir.setBackground(new java.awt.Color(153, 0, 0));
        salir.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/logo_3.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(crear_instructivo, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(agregar_info, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91)
                        .addComponent(buscar_atecedentes, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                        .addComponent(consultar_info, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(104, 104, 104))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(crear_instructivo, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(agregar_info, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscar_atecedentes, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(consultar_info, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(82, 82, 82)
                .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(22, 22, 22))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 802, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(192, 192, 192))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregar_infoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregar_infoActionPerformed
        Agregar_informacion ai=new Agregar_informacion();
        ai.setLocationRelativeTo(null);
        ai.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        ai.setTitle("Agregando documentacion");
        ai.setVisible(true);
    }//GEN-LAST:event_agregar_infoActionPerformed

    private void consultar_infoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultar_infoActionPerformed
        Consulta_de_informacion ci=new Consulta_de_informacion();
        ci.setLocationRelativeTo(null);
        ci.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        ci.setTitle("Consulta de informacion");
        ci.setVisible(true);
    }//GEN-LAST:event_consultar_infoActionPerformed

    private void buscar_atecedentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscar_atecedentesActionPerformed
        Buscar_antecedentes b=new Buscar_antecedentes();
        b.setLocationRelativeTo(null);
        b.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        b.setTitle("Busqueda de antecedentes de causas");
        b.setVisible(true);
    }//GEN-LAST:event_buscar_atecedentesActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        this.dispose();
    }//GEN-LAST:event_salirActionPerformed

    private void crear_instructivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crear_instructivoActionPerformed
        Instructivo_causas ic=new Instructivo_causas();
        ic.setLocationRelativeTo(null);
        ic.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        ic.setTitle("Creacion de instruccion de causas");
        ic.setVisible(true);
    }//GEN-LAST:event_crear_instructivoActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregar_info;
    private javax.swing.JButton buscar_atecedentes;
    private javax.swing.JButton consultar_info;
    private javax.swing.JButton crear_instructivo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton salir;
    // End of variables declaration//GEN-END:variables
}
