/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author XPS 9560
 */
public class Menu_abogado_admin extends javax.swing.JFrame {

    /**
     * Creates new form Menu_abogado
     */
    public Menu_abogado_admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        agregar_info = new javax.swing.JButton();
        consultar_info = new javax.swing.JButton();
        generar_documento = new javax.swing.JButton();
        solicitud_servicio = new javax.swing.JButton();
        reporte_ingresos = new javax.swing.JButton();
        pagos_clientes = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 102));
        jLabel1.setText("Menu abogado administrador");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Opciones a elegir", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 36), new java.awt.Color(51, 153, 0))); // NOI18N

        agregar_info.setBackground(new java.awt.Color(0, 102, 0));
        agregar_info.setText("Agregar informacion");
        agregar_info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregar_infoActionPerformed(evt);
            }
        });

        consultar_info.setBackground(new java.awt.Color(0, 102, 0));
        consultar_info.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        consultar_info.setText("Conultar informacion");
        consultar_info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultar_infoActionPerformed(evt);
            }
        });

        generar_documento.setBackground(new java.awt.Color(0, 102, 0));
        generar_documento.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        generar_documento.setText("Generar documentacion de factibilidad del caso");
        generar_documento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generar_documentoActionPerformed(evt);
            }
        });

        solicitud_servicio.setBackground(new java.awt.Color(0, 102, 0));
        solicitud_servicio.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        solicitud_servicio.setText("Ver solicitudes de servico");
        solicitud_servicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                solicitud_servicioActionPerformed(evt);
            }
        });

        reporte_ingresos.setBackground(new java.awt.Color(0, 102, 0));
        reporte_ingresos.setText("Generar reporte de ingresos");
        reporte_ingresos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reporte_ingresosActionPerformed(evt);
            }
        });

        pagos_clientes.setBackground(new java.awt.Color(0, 102, 0));
        pagos_clientes.setText("Ver pagos realizados por los clientes");
        pagos_clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagos_clientesActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(153, 0, 0));
        jButton4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jButton4.setText("Salir");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/logo 2.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(solicitud_servicio, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(176, 176, 176)
                .addComponent(pagos_clientes, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 158, Short.MAX_VALUE)
                .addComponent(consultar_info, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(231, 231, 231))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(generar_documento)
                .addGap(109, 109, 109)
                .addComponent(agregar_info, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(reporte_ingresos, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(generar_documento, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(agregar_info, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(reporte_ingresos, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(solicitud_servicio, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pagos_clientes, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(consultar_info, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(321, 321, 321)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 691, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregar_infoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregar_infoActionPerformed
        Agregar_informacion ai=new Agregar_informacion();
        ai.setLocationRelativeTo(null);
        ai.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        ai.setTitle("Agregando informacion");
        ai.setVisible(true);
    }//GEN-LAST:event_agregar_infoActionPerformed

    private void consultar_infoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultar_infoActionPerformed
        Consulta_de_informacion i=new Consulta_de_informacion();
        i.setLocationRelativeTo(null);
        i.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        i.setTitle("Consulta de documentos disponibles");
        i.setVisible(true);
    }//GEN-LAST:event_consultar_infoActionPerformed

    private void solicitud_servicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_solicitud_servicioActionPerformed
        Solicitud_de_servicio s=new Solicitud_de_servicio();
        s.setLocationRelativeTo(null);
        s.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        s.setTitle("Solicitudes de los clientes");
        s.setVisible(true);
    }//GEN-LAST:event_solicitud_servicioActionPerformed

    private void reporte_ingresosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reporte_ingresosActionPerformed
        Reporte_ingresos r=new Reporte_ingresos();
        r.setLocationRelativeTo(null);
        r.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        r.setTitle("Creacion de reportes de ingresos");
        r.setVisible(true);
    }//GEN-LAST:event_reporte_ingresosActionPerformed

    private void pagos_clientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagos_clientesActionPerformed
        Ver_pagos_realizados r=new Ver_pagos_realizados();
        r.setLocationRelativeTo(null);
        r.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        r.setTitle("Pagos registrados de los clientes");
        r.setVisible(true);
    }//GEN-LAST:event_pagos_clientesActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void generar_documentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generar_documentoActionPerformed
        Generar_documento_factibilidad gd=new Generar_documento_factibilidad();
        gd.setLocationRelativeTo(null);
        gd.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        gd.setTitle("Generando documento de factibilidad");
        gd.setVisible(true);
        
    }//GEN-LAST:event_generar_documentoActionPerformed

    /**
     * @param args the command line arguments
     */
//    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregar_info;
    private javax.swing.JButton consultar_info;
    private javax.swing.JButton generar_documento;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton pagos_clientes;
    private javax.swing.JButton reporte_ingresos;
    private javax.swing.JButton solicitud_servicio;
    // End of variables declaration//GEN-END:variables
}
